inherit_from: .rubocop_todo.yml
Documentation:
  Enabled: false
EndOfLine:
  Enabled: false
Rails:
  Enabled: true
Style/LeadingCommentSpace:
  Enabled: false

  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
