inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

# Allow classes longer than 100 lines of code
ClassLength:
  Max: 110