inherit_from: .rubocop_todo.yml
<<<<<<< HEAD

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'

Rails:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: false

Style/Documentation:
  Enabled: false
=======
Documentation:
  Enabled: false
EndOfLine:
  Enabled: false
Rails:
  Enabled: true
Style/LeadingCommentSpace:
  Enabled: false

  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
>>>>>>> rubocop
