language: ruby
rvm:
  - 2.0
sudo: required

notifications:
  email:
    recipients:
      - umfarruh@gmail.com
      - ufarruh@gmail.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - bundle exec rubocop
  - bundle exec rspec
