language: ruby
rvm:
  - 2.6.2
sudo: required

notifications:
  email:
    recipients:
      - umfarruh@gmail.com
      - ufarruh@gmail.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always

addons:
  postgresql: "9.4"

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate RAILS_ENV=test

script:
  - bundle exec rspec
  - bundle exec rubocop
